name: Run Tests

on:
  pull_request:
    branches: "**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: iknow_view_models
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        include:
          - ruby-version: '2.7'
            bundle-gemfile: gemfiles/rails_5_2.gemfile
          - ruby-version: '3.0'
            bundle-gemfile: gemfiles/rails_6_0.gemfile
          - ruby-version: '3.1'
            bundle-gemfile: gemfiles/rails_6_1.gemfile
          - ruby-version: '3.2'
            bundle-gemfile: gemfiles/rails_7_0.gemfile

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.bundle-gemfile }}
      DATABASE_URL: "postgres://rails:password@localhost:5432/iknow_view_models"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake test
    - name: Upload result
      uses: actions/upload-artifact@v3
      if: always()
      with:
        path: test/reports/
        name: test_results_${{ matrix.ruby-version }}
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Minitest Tests - ${{ matrix.ruby-version }}
        path: test/reports/*.xml
        reporter: java-junit
